package org.j4el.com.exception;

public enum ExceptionMessage {
    TITLE_ALREADY_EXIST,
    TASK_IN_PAST, ID_NOT_FOUND, CANNOT_UPDATE_TASK, EMPTY_TITLE, EMPTY_LOCATION, INVALID_ID, SCHEDULED_DATE_NULL, INVALID_TASK_STATUS
}
