openapi: "3.0.0"
info:
  version: 1.0.0
  title: Task Creation
  description: Contract for task application
servers:
  - url: localhost:8081
paths:
  /tasks/create:
    post:
      requestBody:
        description: Dto for Creating Task
        required: false
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/CreateTaskDto'
      responses:
        200:
          description: Task Created Successfully
        500:
          description: Internal Server Error
components:
  schemas:
    CreateTaskDto:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        scheduleDate:
          type: string
          format: date
        location:
          type: string